- composer.json
Do not require the meta package `typo3/minimal` but require
the packages that are really required by the package itself.
Do also add a suggestion to install `typo3/testing-framework`
as it is required by the bootstrap.
Fixes #3
> [BUGFIX] Do not require meta package `typo3/minimal`

- src/Reflection/RepositoryFindByMethodReflection.php
Calling a findByXXX method on a repository tries to get the type of
the property from the model. But the reposiory does also allow findBy methods
for values that are not defined in the model but only in the database.
So if the model does not have the certain property we tread it as type mixed.
> Do not fail on calls to MyRepository->findBySomePropNotInModel()

- composer.json
- extension.neon
- src/Type/QueryInterfaceDynamicReturnTypeExtension.php
- src/Type/QueryResultToArrayDynamicReturnTypeExtension.php
- src/Type/RepositoryQueryDynamicReturnTypeExtension.php
- tests/Unit/Type/RepositoryQueryDynamicReturnTypeExtensionTest.php
- tests/Unit/Type/data/custom-query-type.php
This keeps the inferred/declared type of `QueryInterface` and `QueryResultInterface`, if they are already a `GenericObjectType`.
This way, it's possible to not follow the Extbase naming conventions (for whatever reason) and still have correct type analysis results by PhpStan.
Additionally, the changes are covered by Unit tests (which should probably be included in the Travis pipeline).
> Only override type of QueryInterface if not specified

- composer.json
- src/Reflection/RepositoryFindByMethodReflection.php
- tests/Unit/Type/data/repository-stub-files.php
The FooRepository->findByProperty() function must return an
`QueryResultInterface<Foo>` type.
Tests have also been added for that case.
> Fix return type of repository findBy methods

- src/Type/RepositoryFindAllDynamicReturnTypeExtension.php
- stubs/Repository.stub
- tests/Unit/Type/data/repository-stub-files.php
The RepositoryFindAllDynamicReturnTypeExtension does now check where
the findAll method is defined. If it is not overwritten but defined
in the native Repository class, the default behavior, returning a
QueryResultInterface, will be used. If the findAll method is overwritten,
the declaration from that overwrite will be used.
The Repository.stub has been adjusted to now also support and array as
return type for findAll.
> Add possibility to define array return type for Repository->findAll

- src/Helpers/Typo3ClassNamingUtilityTrait.php
- src/Reflection/RepositoryCountByMethodsClassReflectionExtension.php
- src/Reflection/RepositoryFindByMethodReflection.php
- src/Reflection/RepositoryFindMethodsClassReflectionExtension.php
- src/Reflection/RepositoryFindOneByMethodReflection.php
- src/Type/QueryInterfaceDynamicReturnTypeExtension.php
- src/Type/QueryResultToArrayDynamicReturnTypeExtension.php
- src/Type/RepositoryDynamicReturnTypeExtension.php
- src/Type/RepositoryFindAllDynamicReturnTypeExtension.php
- src/Type/RepositoryQueryDynamicReturnTypeExtension.php
Our internal phpstan check does currently fail on TYPO3 main
branch as ClassNamingUtility::translateRepositoryNameToModelName()
does expect a `class-string<RepositoryInterface>` so a `class-string`
is not sufficient anymore.
> Fix internal issue detected by phpstan with TYPO3 HEAD

- composer.json
- src/Helpers/Typo3ClassNamingUtilityTrait.php
- src/Reflection/RepositoryCountByMethodsClassReflectionExtension.php
- src/Reflection/RepositoryFindByMethodReflection.php
- src/Reflection/RepositoryFindMethodsClassReflectionExtension.php
- src/Reflection/RepositoryFindOneByMethodReflection.php
- src/Type/QueryInterfaceDynamicReturnTypeExtension.php
- src/Type/QueryResultToArrayDynamicReturnTypeExtension.php
- src/Type/RepositoryDynamicReturnTypeExtension.php
- src/Type/RepositoryFindAllDynamicReturnTypeExtension.php
- src/Type/RepositoryQueryDynamicReturnTypeExtension.php
To be able to use conditional return types we need to update
the minumum phpstan version to be 1.6.
See https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types
> Require phpstan ^1.6

- build.xml
- composer.json
- src/Helpers/Typo3ClassNamingUtilityTrait.php
- src/Reflection/RepositoryCountByMethodsClassReflectionExtension.php
- src/Reflection/RepositoryFindByMethodReflection.php
- src/Reflection/RepositoryFindMethodsClassReflectionExtension.php
- src/Reflection/RepositoryFindOneByMethodReflection.php
- src/Type/QueryInterfaceDynamicReturnTypeExtension.php
- src/Type/QueryResultToArrayDynamicReturnTypeExtension.php
- src/Type/RepositoryDynamicReturnTypeExtension.php
- src/Type/RepositoryFindAllDynamicReturnTypeExtension.php
- src/Type/RepositoryQueryDynamicReturnTypeExtension.php
If phpstan command is called with "analyse" as command
it does expect the paths that it should scan and does
not respect the configured paths in phpstan.neon anymore.
To fix this issue and make use of the configured paths
again, the `analyse` command has been removed from the
phing build.xml
> Fix phpstan call in phing to respect configured path

- src/Helpers/Typo3ClassNamingUtilityTrait.php
There have been multiple issues in the condition
that does check if the given class does implement the
RepositoryInterface when converting the repository name
to a model name.
1. The condition was not negated
2. The attributes passed to "is_a()" where in the wrong or order.
So the condition was totally broken and did not do what it should do.
> Fix invalid condition in Typo3ClassNamingUtilityTrait

- README.md
- extension.neon
- phpstan.neon
- src/Rule/RequestAttributeValidationRule.php
- src/Type/ContextDynamicReturnTypeExtension.php
- src/Type/RequestDynamicReturnTypeExtension.php
- tests/Unit/Type/RequestGetAttributeDynamicReturnTypeExtensionTest.php
- tests/Unit/Type/data/context-get-aspect-return-types.neon
- tests/Unit/Type/data/context-get-aspect-return-types.php
- tests/Unit/Type/data/request-get-attribute-return-types.neon
- tests/Unit/Type/data/request-get-attribute-return-types.php
The types defined in the `parameters.typo3.contextApiGetAspectMapping`
and `parameters.typo3.requestGetAttributeMapping` can now be more complex
phpDoc types. This is useful if e.g. a request argument can be nullable
or of diffent type.
Tests have been added to test the behavior.
Beside that a validation rule has been added that gives a hint
if a request attribute mapping for phpstan is missing.
> Allow more complex phpdoc types in mappings and add more tests

- .github/workflows/tests.yml
This allows having only a subset of tests when new PHP versions and TYPO3 versions are added (where not all combinations are possible).
> [TASK] Make the test matrix entries explicit

- composer.json
TYPO3 8LTS has reached its end of life quite some time ago, and getting the tests to work (in order to ensure this package works fine with 8LTS) is quite some hassle.
> [TASK] Drop support for TYPO3 8LTS

- composer.json
Otherwise, a test with TYPO3 11LTS with the lowest dependencies will fail in PHP 7.4 due to a missing `str_starts_with` function.
> [BUGFIX] Add `symfony/polyfill-php80` as a dev dependency

- composer.json
As long as this package supports PHP 7.2, it needs to use PHPUnit 8.5 in order to run the tests as PHPUnit 9.5 requires PHP >= 7.3.
> [TASK] Downgrade to PHPUnit 8.5

- composer.json
This avoids pulling in a newer version of this package with breaking changes. (Currently, version with breaking changes is in development.)
> [BUGFIX] Use a bounded dependency on `nikic/php-parser`

- .github/workflows/tests.yml
After the downgrade to PHPUnit 8.5, we now can run the tests on PHP 7.2 as well, ensuring that everything works fine.
> [FEATURE] Add PHP 7.2 to the CI test matrix

- composer.json
This avoids running into long-resolved bugs (while not breaking compatibility).
> [TASK] Raise the dependencies to the latest minor/bugfix version

- stubs/GeneralUtility.stub
Now the stub is in line with what TYPO3 11LTS has.
> [TASK] Improve the `GeneralUtility::makeInstance` stub

- src/Rule/RequestAttributeValidationRule.php
- src/Type/RequestDynamicReturnTypeExtension.php
If `psr/http-message` is not installed, we now fail hard with a helpful exception message.
> [BUGFIX] Stop relying on transitive dependencies

- stubs/GeneralUtility.stub
For variable arguments, the type annotation needs to match the type of the single arguments, not an array of the single arguments.
This change parallels that in the TYPO3 Core:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/78080
> [BUGFIX] Fix type annotation in the `GeneralUtility` stub

- composer.json
- extension.neon
- src/Stubs/StubFilesExtensionLoader.php
The TYPO3 core is going to fix and extend some
of its types and annocations. We have to react
at some places and must not load some stubs anymore in newer TYPO3 versions.
Issue: #114
> Load TYPO3 version specific stubs

- src/Type/RequestDynamicReturnTypeExtension.php
- tests/Unit/Type/data/request-get-attribute-return-types.php
Whenever the `$request->getAttribute()` method is called, it is possible to provide a default value in case the given argument resolves to `null`. Thus, the default value should be part of the return type.
Example:
```php
use TYPO3\CMS\Core\Site\Entity\NullSite;
use TYPO3\CMS\Core\Site\Entity\Site;
/** @var NullSite|Site $site */
$site = $request->getAttribute('site', new NullSite());
```
> [BUGFIX] Include default value passed to `$request->getAttribute()`

- src/Type/QueryInterfaceDynamicReturnTypeExtension.php
In some rare cases (only in combination with rector?) the QueryInterfaceDynamicReturnTypeExtension failed with an exception as it has been tried to convert a Repository name to a model name even if the QueryInterface was not used in a Repository. It is checked if we're in the scope of a repository and if not we use a mixed type as we could not find out which type exactly it is.
> [BUGFIX] Fix fatal error in QueryInterfaceDynamicReturnTypeExtension

- extension.neon
The current content object is now available as request attribute - see https://forge.typo3.org/issues/100623
This change updates `typo3.requestGetAttributeMapping`, so `currentContentObject` can be resolved
> [TASK] Add currentContentObject to typo3.requestGetAttributeMapping

- extension.neon
- src/Type/UserAspectGetDynamicReturnTypeExtension.php
- tests/Unit/Type/UserAspectGetDynamicReturnTypeExtension/UserAspectGetDynamicReturnTypeExtensionTest.php
- tests/Unit/Type/UserAspectGetDynamicReturnTypeExtension/data/user-aspect-get-return-types.php
Hi,
this is a dynamic return type extension for `UserAspect::get()`. There are dedicated getters but since `get()` exists and is in use, I'd like to have phpstan type support here.
Thanks for having a look.
Cheers. :)
> [FEATURE] Add dynamic return type extension for UserAspect::get()

- composer.json
At the moment the branch alias is not relevant for us
> TASK: Remove branch alias

- src/Reflection/RepositoryCountByMethodsClassReflectionExtension.php
- src/Reflection/RepositoryFindMethodsClassReflectionExtension.php
- tests/Unit/Type/data/repository-stub-files.php
If a repository is abstract we must not try to find a model based on the repository name.
Resolves: #140
> [BUGFIX] Do not try to find model for abstract repository

- composer.json
This version of PHPStan makes some test-related methods static, which is required for newer PHPUnit versions (where data providers are required to be static).
> [TASK] Bump PHPStan to ^1.10.9

- .github/workflows/tests.yml
- composer.json
With the PHP version requirement being >= 7.4, usage of this package for extensions that still support TYPO3 10LTS (and hence usually also support TYPO3 7.2 and 7.3) was limited anyway.
> [!!!][TASK] Drop support for TYPO3 10LTS

- src/Reflection/RepositoryCountByMethodReflection.php
- src/Reflection/RepositoryCountByMethodsClassReflectionExtension.php
- src/Reflection/RepositoryCountByParameterReflection.php
- src/Reflection/RepositoryFindByMethodReflection.php
- src/Reflection/RepositoryFindByParameterReflection.php
- src/Reflection/RepositoryFindMethodsClassReflectionExtension.php
- src/Reflection/RepositoryFindOneByMethodReflection.php
- src/Rule/ContextAspectValidationRule.php
- src/Rule/RequestAttributeValidationRule.php
- src/Rule/SiteAttributeValidationRule.php
- src/Rule/ValidatorResolverOptionsRule.php
- src/Rule/ValueObject/ValidatorOptionsConfiguration.php
- src/Stubs/StubFilesExtensionLoader.php
- src/Type/ContextDynamicReturnTypeExtension.php
- src/Type/DateTimeAspectGetDynamicReturnTypeExtension.php
- src/Type/GeneralUtilityGetIndpEnvDynamicReturnTypeExtension.php
- src/Type/ObjectManagerDynamicReturnTypeExtension.php
- src/Type/PropertyMapperReturnTypeExtension.php
- src/Type/RepositoryDynamicReturnTypeExtension.php
- src/Type/RepositoryFindAllDynamicReturnTypeExtension.php
- src/Type/RepositoryQueryDynamicReturnTypeExtension.php
- src/Type/RequestDynamicReturnTypeExtension.php
- src/Type/SiteDynamicReturnTypeExtension.php
- src/Type/UserAspectGetDynamicReturnTypeExtension.php
- src/Type/ValidatorResolverDynamicReturnTypeExtension.php
As we are on PHP 7.4 already, let´s go for native Type Declarations and drop the docblocks
> [TASK] Use Type declarations and remove redundant docblocks

- stubs/ObjectStorage.stub
- stubs/QueryResultInterface.stub
The types in the stubs should be as narrow as possible: When an array with continuous integer keys starting with 0 is returned, this is a `list`, and it should be annotated as such.
> [TASK] Use `list` whereever possible

- stubs/ObjectStorage.stub
It looks like PHPStan 1.11.9 considers the offending line to be different in version 1.11.9.
To be compatible with both PHPStan <= 1.11.9 and 1.11.9, we now need two `@phpstan-ignore-next-line` entries.
Fixes #167
> [BUGFIX] Avoid warnings about `ObjectStorage` with PHPStan 1.11.9

- stubs/ObjectStorage.stub
- stubs/QueryInterface.stub
- stubs/QueryResult.stub
- stubs/QueryResultInterface.stub
- stubs/Repository.stub
The Core recently has received some improvements on the type annotations/declerations. Port those over to our stubs.
Also rearrage some union type to have `null` always last.
> [TASK] Port some type annotation improvements from the Core

- extension.neon
This got introduced with TYPO3 v13 LTS, see:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Feature-102715-NewFrontendpageinformationRequestAttribute.html
Resolves: #175
> [TASK] Add new frontend.page.information request attribute

- extension.neon
- phpstan.neon
- src/Type/ObjectStorageDynamicReturnTypeExtension.php
- stubs/ObjectStorage.stub
- stubs/QueryResultInterface.stub
- tests/Unit/Type/QueryResultToArrayDynamicReturnTypeExtension/data/query-result-to-array.php
- tests/Unit/Type/data/object-storage-stub-files.php
The object storage offsetGet() is not compatible with the
ArrayAccess interface but does some TYPO3 sepcific stuff.
We can't set the correct return type via a stub as phpstan
will complain that the return type is not compatible with
the interface.
To work around this we have to implement a dynamic return
type extension again.
> Fix invalid interface implementation by dynamic return type

- tests/Unit/Type/data/custom-query-type.php
The execute method has a boolean argument that
defines if a raw result should be returned.
This means that no object mapping is done but
an array containing the result values is returned.
It is now also supported to not just pass constant boolean values but a variable containing a boolean to the execute function. In this case it's not clear if a raw result or objects should be returned
so we do now return a union type containing both.
> Fix return type of QueryInterface::execute()
