src/Reflection/RepositoryFindByMethodReflection.php, src/Reflection/RepositoryFindByParameterReflection.php, src/Reflection/RepositoryFindOneByMethodReflection.php, src/Type/GeneralUtilityDynamicReturnTypeExtension.php
=> [BUGFIX] Update reflections to be compatible with 0.10 interfaces

composer.json
This pull request, adds support for phpstan extension installer.
=> Add support for extension installer

.gitignore, composer.json, src/Reflection/RepositoryFindByMethodReflection.php, src/Reflection/RepositoryFindByParameterReflection.php, src/Reflection/RepositoryFindOneByMethodReflection.php
=> Add phpstan 0.12 compatibility

extension.neon, src/Type/ValidatorResolverDynamicReturnTypeExtension.php
Adds return-type hints for ValidatorResolver->createValidator()
=> Add dynamic return type extension for ValidatorResolver

extension.neon, phpstan.neon, src/Type/ContextDynamicReturnTypeExtension.php
Like in the last PR, I'm quite new to phpstan in general, and this project specifically.
Don't know if we can use the actual implementation of the method instead of duplicating the switch/case statement here.
=> Add dynamic return type extension for Context->getAspect

extension.neon
=> Add some TYPO3 methods as earlyTerminatingMethodCalls

README.md, extension.neon, tests/Unit/Type/ContextDynamicReturnTypeExtensionTest.php, tests/Unit/Type/data/context-get-aspect-return-types.php
fixes https://github.com/sascha-egerer/phpstan-typo3/issues/54
=> Fixed class paths in context getAspect mapping

README.md, extension.neon, src/Type/RequestDynamicReturnTypeExtension.php
Fixes https://github.com/sascha-egerer/phpstan-typo3/issues/50
I'm not entirely sure if I did that right... 
Please let me know your thoughts.
=> Make attributes of Request Api configurable

phpstan.neon, stubs/ObjectStorage.stub, tests/Unit/Type/ObjectStorageStubFileTest.php, tests/Unit/Type/data/object-storage-stub-files.php
=> Allow index for ObjectStorage to be int

.github/workflows/tests.yml, composer.json, src/Type/ObjectManagerDynamicReturnTypeExtension.php
=> [FEATURE] Add support for TYPO3 12

extension.neon, src/Type/PropertyMapperReturnTypeExtension.php, tests/Unit/Type/PropertyMapperReturnTypeExtension/PropertyMapperReturnTypeExtensionTest.php, tests/Unit/Type/PropertyMapperReturnTypeExtension/data/property-converter-types.php
=> TASK: Add PropertyMapperReturnTypeExtension

.github/FUNDING.yml, build.xml, composer.json, phpcs.xml
This will remove unrelated changes in contributions (where the contributors might want to autoformat the changed files).
=> [CLEANUP] Autoformat the non-PHP files according to the `.editorconfig`

src/Helpers/Typo3ClassNamingUtilityTrait.php, src/Reflection/RepositoryFindMethodsClassReflectionExtension.php, src/Rule/RequestAttributeValidationRule.php, src/Rule/ValidatorResolverOptionsRule.php, src/Service/ValidatorClassNameResolver.php, src/Type/PropertyMapperReturnTypeExtension.php, src/Type/RepositoryDynamicReturnTypeExtension.php, src/Type/RepositoryFindAllDynamicReturnTypeExtension.php, stubs/DomainObjectInterface.stub, tests/Unit/Rule/ValidatorResolverOptionsRule/ValidatorResolverOptionsRuleTest.php, tests/Unit/Type/ContextDynamicReturnTypeExtensionTest.php, tests/Unit/Type/ObjectStorageStubFileTest.php, tests/Unit/Type/PropertyMapperReturnTypeExtension/PropertyMapperReturnTypeExtensionTest.php, tests/Unit/Type/QueryFactoryStubFileTest.php, tests/Unit/Type/RepositoryQueryDynamicReturnTypeExtensionTest.php, tests/Unit/Type/RepositoryStubFileTest.php, tests/Unit/Type/RequestGetAttributeDynamicReturnTypeExtensionTest.php, tests/Unit/Type/SiteGetAttributeDynamicReturnTypeExtensionTest.php, tests/Unit/Type/data/custom-query-type.php, tests/Unit/Type/data/repository-stub-files.php, tests/Unit/Type/data/request-get-attribute-return-types.php
This will remove unrelated changes in contributions (where the contributors might want to autoformat the changed files).
=> [CLEANUP] Autoformat the PHP files with PhpStorm

src/Type/RepositoryFindAllDynamicReturnTypeExtension.php
The cheaper condition in an `if` statement should come first.
=> [TASK] Reorder a condition to improve performance

composer.json, src/Type/QueryResultToArrayDynamicReturnTypeExtension.php, tests/Unit/Type/QueryResultToArrayDynamicReturnTypeExtension/QueryResultToArrayDynamicReturnTypeExtensionTest.php, tests/Unit/Type/QueryResultToArrayDynamicReturnTypeExtension/data/query-result-to-array.php, tests/Unit/Type/data/repository-stub-files.php
=> [BUGFIX] Make QueryResultToArrayDynamicReturnTypeExtension work with CompoundType

phpstan.neon, src/Type/QueryResultToArrayDynamicReturnTypeExtension.php, src/Type/RepositoryFindAllDynamicReturnTypeExtension.php, tests/Unit/Type/QueryResultToArrayDynamicReturnTypeExtension/data/query-result-to-array.php
Adjust the return type of Repository::findAll based on context
References #103
=> [TASK] Make return type of Repository::findAll() more stable

extension.neon, phpstan.neon, src/Type/MathUtilityTypeSpecifyingExtension.php, tests/Unit/Type/MathUtilityTypeSpecifyingExtension/MathUtilityTypeSpecifyingExtensionTest.php, tests/Unit/Type/MathUtilityTypeSpecifyingExtension/data/MathUtilityTest.php
=> TASK: Add MathUtilityTypeSpecifyingExtension

extension.neon, src/Type/GeneralUtilityGetIndpEnvDynamicReturnTypeExtension.php, tests/Unit/Type/GeneralUtilityGetIndpEnvDynamicReturnTypeExtension/GeneralUtilityGetIndpEnvDynamicReturnTypeExtensionTest.php, tests/Unit/Type/GeneralUtilityGetIndpEnvDynamicReturnTypeExtension/data/GeneralUtilityGetIndpEnvTest.php
=> TASK: Add dynamic return type extension for getIndpEnv

extension.neon
* Added `frontend.controller` - see https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendController.html
* Added `frontend.typoscript` - see https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendTyposcript.html
=> Added `frontend.controller` and `frontend.typoscript` request attribute mapping

README.md
=> TASK: Add better documentation

composer.json
=> TASK: Add static analysis as keyword

extension.neon, stubs/EventDispatcher.stub
=> TASK: Provide stub for EventDispatcherInterface
